
 CREATE TABLE IF NOT EXISTS PUBLIC.barangay (
    id SERIAL NOT NULL,
    code VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    distribution_utility_id INTEGER,
    city_id INTEGER NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified_at TIMESTAMP DEFAULT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "barangay_distribution_utility_fk" FOREIGN KEY ("distribution_utility_id") REFERENCES "distribution_utility" ("id"),
    CONSTRAINT "barangay_city_fk" FOREIGN KEY ("city_id") REFERENCES "city" ("id"),
    CONSTRAINT "barangay_code_distribution_utility_city_unique" UNIQUE ("code", "distribution_utility_id", "city_id")
 );

DO $$
    -- `Distribution Utility`
	DECLARE dlpcId INTEGER := (SELECT "id" FROM "distribution_utility" WHERE "code" = 'DLPC');
	DECLARE vecoId INTEGER := (SELECT "id" FROM "distribution_utility" WHERE "code" = 'VECO');

	-- `City`
	DECLARE bunId INTEGER := (SELECT "id" FROM "city" WHERE "code" = 'BUN');
	DECLARE carId INTEGER := (SELECT "id" FROM "city" WHERE "code" = 'CAR');
    DECLARE cebId INTEGER := (SELECT "id" FROM "city" WHERE "code" = 'CEB');
    DECLARE conId INTEGER := (SELECT "id" FROM "city" WHERE "code" = 'CON');
    DECLARE davId INTEGER := (SELECT "id" FROM "city" WHERE "code" = 'DAV');
	DECLARE dujId INTEGER := (SELECT "id" FROM "city" WHERE "code" = 'DUJ');
	DECLARE kapId INTEGER := (SELECT "id" FROM "city" WHERE "code" = 'KAP');
    DECLARE lasId INTEGER := (SELECT "id" FROM "city" WHERE "code" = 'LAS');
	DECLARE lilId INTEGER := (SELECT "id" FROM "city" WHERE "code" = 'LIL');
	DECLARE malId INTEGER := (SELECT "id" FROM "city" WHERE "code" = 'MAL');
	DECLARE mandId INTEGER := (SELECT "id" FROM "city" WHERE "code" = 'MAND');
	DECLARE mingId INTEGER := (SELECT "id" FROM "city" WHERE "code" = 'MING');
	DECLARE nagaId INTEGER := (SELECT "id" FROM "city" WHERE "code" = 'NAGA');
	DECLARE panId INTEGER := (SELECT "id" FROM "city" WHERE "code" = 'PAN');
	DECLARE paqId INTEGER := (SELECT "id" FROM "city" WHERE "code" = 'PAQ');
	DECLARE sfernId INTEGER := (SELECT "id" FROM "city" WHERE "code" = 'SFERN');
	DECLARE stomId INTEGER := (SELECT "id" FROM "city" WHERE "code" = 'STOM');
	DECLARE talId INTEGER := (SELECT "id" FROM "city" WHERE "code" = 'TAL');
BEGIN
    INSERT INTO PUBLIC.barangay
    (code, description, distribution_utility_id, city_id, created_at, modified_at)
    VALUES
        ('CARCALE', 'Alejal', dlpcId, carId, CURRENT_TIMESTAMP, NULL),
        ('CARCANI', 'Anibongan', dlpcId, carId, CURRENT_TIMESTAMP, NULL),
        ('CARCASU', 'Asuncion', dlpcId, carId, CURRENT_TIMESTAMP, NULL),
        ('CARCCAM', 'Camiling', dlpcId, carId, CURRENT_TIMESTAMP, NULL),
        ('CARCCARPRO' ,'Prop', dlpcId, carId, CURRENT_TIMESTAMP, NULL),
        ('CARCCEB', 'Cebulano', dlpcId, carId, CURRENT_TIMESTAMP, NULL),
        ('CARCGUA', 'Guadalupe', dlpcId, carId, CURRENT_TIMESTAMP, NULL),
        ('CARCISI', 'Ising', dlpcId, carId, CURRENT_TIMESTAMP, NULL),
        ('CARCLAPAZ', 'La Paz', dlpcId, carId, CURRENT_TIMESTAMP, NULL),
        ('CARCLOWMAB' ,'Lower Mabuhay', dlpcId, carId, CURRENT_TIMESTAMP, NULL),
        ('CARCMAB', 'Mabuhay', dlpcId, carId, CURRENT_TIMESTAMP, NULL),
        ('CARCMAG', 'Magsaysay', dlpcId, carId, CURRENT_TIMESTAMP, NULL),
        ('CARCMAN', 'Mangalcal', dlpcId, carId, CURRENT_TIMESTAMP, NULL),
        ('CARCSAL', 'Salvacion', dlpcId, carId, CURRENT_TIMESTAMP, NULL),
        ('CARCSANISI', 'SanIsidro', dlpcId, carId, CURRENT_TIMESTAMP, NULL),
        ('CARCSTONIN', 'StoNino', dlpcId, carId, CURRENT_TIMESTAMP, NULL),
        ('CARCTABA', 'Taba', dlpcId, carId, CURRENT_TIMESTAMP, NULL),
        ('CARCTIB', 'Tibulao', dlpcId, carId, CURRENT_TIMESTAMP, NULL),
        ('CARCTUB', 'Tubod', dlpcId, carId, CURRENT_TIMESTAMP, NULL),
        ('CARCTUG', 'Tuganay', dlpcId, carId, CURRENT_TIMESTAMP, NULL),
        ('CARMAB', 'Mabaus', dlpcId, carId, CURRENT_TIMESTAMP, NULL),
        ('CARMIN', 'Minda', dlpcId, carId, CURRENT_TIMESTAMP, NULL),
        ('DAVC10A', '10A', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC11B', '11B', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC12B', '12B', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC13B', '13B', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC14B', '14B', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC15B', '15B', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC16B', '16B', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC17B', '17B', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC18B', '18B', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC19B', '19B', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC1A', '1A', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC20B', '20B', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC21C', '21C', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC22C', '22C', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC23C', '23C', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC24C', '24C', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC25C', '25C', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC26C', '26C', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC27C', '27C', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC28C', '28C', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC29C', '29C', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC2A', '2A', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC30C', '30C', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC31D', '31D', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC32D', '32D', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC33D', '33D', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC34D', '34D', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC35D', '35D', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC36D', '36D', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC37D', '37D', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC38D', '38D', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC39D', '39D', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC3A', '3A', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC40D', '40D', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC4A', '4A', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC5A', '5A', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC6A', '6A', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC7A', '7A', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC8A', '8A', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC9A', '9A', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCACA', 'Acacia', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCAGDPRO', 'Agdao Proper', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCALA', 'Alambre', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCANGA', 'Angalan', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCANGL', 'Angliongto', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCATAOWE', 'Atan Owe', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCBAG', 'Baganihan', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCBAGAPL', 'Bago Aplaya', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCBAGGAL', 'Bago Gallera', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCBAGPRO', 'Baguio Proper', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCBALA', 'Balagunan', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCBALING', 'Balingaeng', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCBALIOK', 'Baliok', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCBANHEI', 'Bangkas Heights', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCBAN', 'Bantol', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCBAR', 'Baracatan', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCBAT', 'Bato', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCBAY', 'Bayabas', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCBIAESC', 'Biao Escuela', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCBIAGUI', 'Biao Guianga', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCBIAJOA', 'Biao Joaquin', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCBIAMAT', 'BiaoMatina', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCBIN', 'Binugao', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCBOB', 'Bobongon', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCBUC', 'Bucana', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCBUD', 'Buda', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCBUHPRO', 'Buhangin Proper', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCBUNPRO', 'Bunawan Proper', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCCAB', 'Cabantian', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCCAD', 'Cadalian', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCCALPRO', 'Calinan Proper', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCCAL', 'Callawa', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCCAM', 'Camansi', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCCAR', 'Carmen', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCCASANG', 'Casig Ang', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCCATGRA', 'Cat Grande', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCCAT', 'Catigan', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCCATPEQ', 'Cat Pequeno', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCCAW', 'Cawayan', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCCENSANJUA', 'Centro San Juan', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCCOL', 'Colosas', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCCOM', 'Communal', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCCRSBAY', 'Crssing Bayabas', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCDAC', 'Dacudao', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCDALAG', 'Dalag', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCDALAGDAG', 'Dalagdag', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCDALIAO', 'Daliao', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCDALIAON', 'Daliaon', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCDALPLN', 'Daliaon Plnttn', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCDATSAL', 'Datu Salumay', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCDOM', 'Dominga', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCDUM', 'Dumoy', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCEDE', 'Eden', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCESP', 'Esperanza', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCFAT', 'Fatima', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCGAT', 'Gatungan', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCGOVVDUT', 'Gov V Duterte', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCGUMA', 'Gumalang', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCGUMI', 'Gumitan', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCHIZ', 'Hizon', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCILA', 'Ilang', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCINA', 'Inayangan', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCIND', 'Indangan', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCKAT', 'Katipunan', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCKIL', 'Kilate', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCKIM', 'Kimamon', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCKIN', 'Kinamayan', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCLAC', 'Lacson', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCLALIB', 'La Libertad', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCLAMA', 'Lamanan', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCLAMP', 'Lampiano', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCLAN', 'Langub', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCLAPLAP', 'Lapu Lapu', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCLAS', 'Lasang', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCLEOGAR', 'Leon Garcia', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCLIZ', 'Lizada', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCLOSAMI', 'LosAmigos', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCLUB', 'Lubogan', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCLUM', 'Lumiad', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCLUNOG', 'Lunga Og', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCMAA', 'Maa', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCMAB', 'Mabuhay', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCMAGS', 'Magsaysay', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCMAGT', 'Magtuod', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCMAGW', 'Magwawa', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCMAH', 'Mahayag', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCMALAB', 'Malabog', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCMALAG', 'Malagos', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCMALA', 'Malamba', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCMANA', 'Manambulan', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCMAND', 'Mandug', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCMANGUI', 'Manuel Guianga', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCMAP', 'Mapula', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCMAR', 'Marapangi', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCMARPRO', 'Marilog Proper', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCMATAPL', 'Matina Aplaya', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCMATCRO', 'Matina Crossing', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCMATPAN', 'Matina Pangi', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCMEG', 'Megcawayan', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCMIN', 'Mintal', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCMUD', 'Mudiang', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCMUL', 'Mulig', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCNEWCAR', 'New Carmen', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCNEWVAL', 'New Valencia', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCNEWVIS', 'New Visayas', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCOSH', 'Oshiro', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCPAM', 'Pampanga', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCPANA', 'Panacan', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCPAND','Pandaitan', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCPANG','Pangyan', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCPANT','Pantaron', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCPAQPRO','Paquibato Prop', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCPAREMB', 'Paradise Embac', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCPAY', 'Payalum', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCPBAN', 'P Bangoy', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCRCAS', 'R Castillo', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCRIV', 'Riverside', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCSALAP', 'Salapawan', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCSALAY', 'Salaysay', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCSALO', 'Saloy', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCSALV', 'Salvacion', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCSANANT', 'San Antonio', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCSANISI', 'San Isidro', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCSANJOS', 'San Jose', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCSANMIG', 'San Miguel', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCSANVIC', 'San Vicente', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCSAS', 'Sasa', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCSIB', 'Sibulan', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCSIRA', 'Sirawan', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCSIRI', 'Sirib', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCSTONIN', 'Sto Nino', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCSTOTOM', 'Sto Tomas', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCSUA', 'Suawan', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCSUB', 'Subasta', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCSUM', 'Sumimao', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCTAC', 'Tacunan', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCTAGA', 'Tagakpan', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCTAGL', 'Tagluno', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCTAGU', 'Tagurano', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCTALA', 'Talandang', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCTALO', 'Talomo', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCTALPRO', 'Talomo Proper', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCTALRIV', 'Talomo River', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCTAMA', 'Tamayong', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCTAMB', 'Tambobong', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCTAMU', 'Tamugan', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCTAP', 'Tapak', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCTAW', 'Tawan Tawan', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCTIBULOY', 'Tibuloy', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCTIBUNG', 'Tibungco', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCTIG', 'Tigatto', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCTMON', 'T Monteverde', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCTORPOB', 'Toril Poblacion', dlpcId, davId,CURRENT_TIMESTAMP, NULL),
        ('DAVCTUGPRO', 'Tugbok Proper', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCTUL', 'Tulalian', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCTUN', 'Tungkalan', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCUBA', 'Ubalde', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCULA', 'Ula', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCWAA', 'Waan', dlpcId, davId, CURRENT_TIMESTAMP,NULL),
        ('DAVCWAN', 'Wangan', dlpcId, davId,CURRENT_TIMESTAMP, NULL),
        ('DAVCWAQU', 'WAquino', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCWIN', 'Wines', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('DUJCCABANG', 'Cabay Angan', dlpcId, dujId, CURRENT_TIMESTAMP, NULL),
        ('DUJCDUJ', 'Dujali', dlpcId, dujId, CURRENT_TIMESTAMP, NULL),
        ('DUJCNEWCAS', 'New Casay', dlpcId, dujId, CURRENT_TIMESTAMP, NULL),
        ('DUJCSAL', 'Salvacion', dlpcId, dujId, CURRENT_TIMESTAMP, NULL),
        ('DUJCTAN', 'Tanglaw', dlpcId, dujId, CURRENT_TIMESTAMP, NULL),
        ('DUJMAG', 'Magupising', dlpcId, dujId, CURRENT_TIMESTAMP, NULL),
        ('KAPCKAP', 'Kapalong', dlpcId, kapId, CURRENT_TIMESTAMP, NULL),
        ('KAPCLUN', 'Luna', dlpcId, kapId, CURRENT_TIMESTAMP, NULL),
        ('KAPCPAGASA', 'PagAsa', dlpcId, kapId, CURRENT_TIMESTAMP, NULL),
        ('KAPCSAM', 'Sampao', dlpcId, kapId, CURRENT_TIMESTAMP, NULL),
        ('KAPMAM', 'Mamacao', dlpcId, kapId, CURRENT_TIMESTAMP, NULL),
        ('MARAPOPAR', 'Marilog Apo Park', dlpcId, davId, CURRENT_TIMESTAMP, NULL),
        ('PANCADFLO', 'Ad Floirendo', dlpcId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCBUE', 'Buenavista', dlpcId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCCAC', 'Cacao', dlpcId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCCAG', 'Cagangohan', dlpcId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCCON', 'Consolacion', dlpcId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCDAL', 'Dalisay', dlpcId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCDAP', 'Dapco', dlpcId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCDATABD', 'Datu Abdul', dlpcId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCGRE', 'Gredu', dlpcId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCJPLAU', 'Jp Laurel', dlpcId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCKAS', 'Kasilak', dlpcId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCKAT', 'Katipunan', dlpcId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCKAU', 'Kauswagan', dlpcId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCKIO', 'Kiotoy', dlpcId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCLIC', 'Licanan', dlpcId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCLITPAN', 'Little Panay', dlpcId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCLOWPAN', 'Lower Panaga', dlpcId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCMABU', 'Mabunao', dlpcId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCMAD', 'Maduao', dlpcId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCMAL', 'Malativas', dlpcId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCMANA', 'Manay', dlpcId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCNAN', 'Nanyo', dlpcId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCNEWAKL', 'New Aklan', dlpcId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCNEWMAL', 'New Malitbog', dlpcId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCNEWPAN', 'New Pandan', dlpcId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCNEWVIS', 'New Visayas', dlpcId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCPAN', 'Panabo City', dlpcId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCQUE', 'Quezon', dlpcId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCSAL', 'Salvacion', dlpcId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCSANFRA', 'San Francisco', dlpcId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCSANNIC', 'San Nicolas', dlpcId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCSANPED', 'San Pedro', dlpcId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCSANROQ', 'San Roque', dlpcId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCSANVIC', 'San Vicente', dlpcId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCSIN', 'Sindaton', dlpcId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCSOUDAV', 'Southern Davao', dlpcId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCSTACRU', 'StaCruz', dlpcId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCSTONIN', 'StoNino', dlpcId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCTAGO', 'Tagorot', dlpcId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCTAGP', 'Tagpore', dlpcId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCTIB', 'Tibungol', dlpcId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCWATFAL', 'Water Falls', dlpcId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANKAT','Katualan', dlpcId, panId, CURRENT_TIMESTAMP, NULL),
        ('STOTOMNEWKAT', 'New Katipunan', dlpcId, stomId, CURRENT_TIMESTAMP, NULL),
        ('STOTOMNEWVIS', 'New Visayas', dlpcId, stomId, CURRENT_TIMESTAMP, NULL),
        ('STOTOMSAL', 'Salvacion', dlpcId, stomId, CURRENT_TIMESTAMP, NULL),
        ('STOTOMSANVIC', 'San Vicente', dlpcId, stomId, CURRENT_TIMESTAMP, NULL),
        ('CARCALE', 'Alejal', vecoId, carId, CURRENT_TIMESTAMP, NULL),
        ('CARCANI', 'Anibongan', vecoId, carId, CURRENT_TIMESTAMP, NULL),
        ('CARCASU', 'Asuncion', vecoId, carId, CURRENT_TIMESTAMP, NULL),
        ('CARCCAM', 'Camiling', vecoId, carId, CURRENT_TIMESTAMP, NULL),
        ('CARCCARPRO', 'Prop', vecoId, carId, CURRENT_TIMESTAMP, NULL),
        ('CARCCEB', 'Cebulano', vecoId, carId, CURRENT_TIMESTAMP, NULL),
        ('CARCGUA', 'Guadalupe', vecoId, carId, CURRENT_TIMESTAMP, NULL),
        ('CARCISI', 'Ising', vecoId, carId, CURRENT_TIMESTAMP, NULL),
        ('CARCLAPAZ', 'La Paz', vecoId, carId, CURRENT_TIMESTAMP, NULL),
        ('CARCLOWMAB', 'Lower Mabuhay', vecoId, carId, CURRENT_TIMESTAMP, NULL),
        ('CARCMAB', 'Mabuhay', vecoId, carId, CURRENT_TIMESTAMP, NULL),
        ('CARCMAG', 'Magsaysay', vecoId, carId, CURRENT_TIMESTAMP, NULL),
        ('CARCMAN', 'Mangalcal', vecoId, carId, CURRENT_TIMESTAMP, NULL),
        ('CARCSAL', 'Salvacion', vecoId, carId, CURRENT_TIMESTAMP, NULL),
        ('CARCSANISI', 'SanIsidro', vecoId, carId, CURRENT_TIMESTAMP, NULL),
        ('CARCSTONIN', 'StoNino', vecoId, carId, CURRENT_TIMESTAMP, NULL),
        ('CARCTABA', 'Taba', vecoId, carId, CURRENT_TIMESTAMP, NULL),
        ('CARCTIB', 'Tibulao', vecoId, carId, CURRENT_TIMESTAMP, NULL),
        ('CARCTUB', 'Tubod', vecoId, carId, CURRENT_TIMESTAMP, NULL),
        ('CARCTUG', 'Tuganay', vecoId, carId, CURRENT_TIMESTAMP, NULL),
        ('CARMAB', 'Mabaus', vecoId, carId, CURRENT_TIMESTAMP, NULL),
        ('CARMIN', 'Minda', vecoId, carId, CURRENT_TIMESTAMP, NULL),
        ('CEBCADL', 'Adlaon', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCAGS', 'Agsungot', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCAPA', 'Apas', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCBAB', 'Babag', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCBAC', 'Bacayan', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCBAN', 'Banilad', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCBAR', 'Barrio Luz', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCBASMAM', 'Basak Mambaling', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCBASPAR', 'Basak Pardo', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCBASNIC', 'Basak San Nicolas', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCBIN', 'Binaliw', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCBON', 'Bon Bon', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCBUD', 'Budla An', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCBUH', 'Buhisan', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCBUL', 'Bulacao Pardo', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCBUO', 'Buot Taup', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCBUS', 'Busay', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCCAL', 'Calamba', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCCAMBIN', 'Cambinocot', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCCAMPUT', 'Camputhaw', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCCAP', 'Capitol Site', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCCAR', 'Carreta', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCCEB', 'Cebu Port Authority', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCCEN', 'Center Island', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCCOGPAR', 'Cogon Pardo', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCCOGRAM', 'Cogon Ramos', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCDAY', 'Day As', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCDON', 'Dona Cristina Village', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCDUL', 'Duljo Fatima', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCERM', 'Ermita', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCGUA', 'Guadalupe', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCGUB', 'Guba', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCHIP', 'Hipodromo', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCINA', 'Inayawan', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCKALUB', 'Kalubihan', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCKALUN', 'Kalunasan', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCKAM', 'Kamagayan', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCKAS', 'Kasambagan', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCKIN', 'Kinasang An', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCLAB', 'Labangon', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCLAH', 'Lahug', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCLOR', 'Lorega San Miguel', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCLUS', 'Lusaran', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCMBN', 'Mabini', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCMBL', 'Mabolo', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCMAL', 'Malubog', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCMAM', 'Mambaling', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCNOR', 'North Reclamation Area', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCPCNTRL', 'Pahina Central', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCPSNNIC', 'Pahina San Nicolas', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCPAM', 'Pamutan', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCPARIAN', 'Pari An', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCPARIL', 'Paril', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCPAS', 'Pasil', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCPIT', 'Pit Os', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCPOB', 'Poblacion Pardo', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCPUL', 'Pulangbato', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCPUNGSIB', 'Pung Ol Sibugay', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCPUNPRNC', 'Punta Princesa', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCQUI', 'Quiot Pardo', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCREC', 'Reclamation Area', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCSAM1', 'Sambag1', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCSAM2', 'Sambag2', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCSNANT', 'San Antonio', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCSNJS', 'San Jose', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCSNNIC', 'San Nicolas Proper', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCSNROQ', 'San Roque', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCSNTCRUZ', 'Santa Cruz', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCSNTONINO', 'Santo Nino', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCSAP', 'Sapangdaku', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCSAW', 'Sawang Calero', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCSIN', 'Sinsin', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCSIR', 'Sirao', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCSKY', 'Skywalk', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCSUB', 'Suba', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCSUD1', 'Sudlon1', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCSUD2', 'Sudlon2', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCTAB', 'Tabunan', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCTAG', 'TagbaO', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCTAL', 'Talamban', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCTAP', 'Taptap', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCTEJ', 'Tejero', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCTIN', 'Tinago', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCTIS', 'Tisa', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCTOO', 'Toong', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCTPA', 'TPadilla', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CEBCZAP', 'Zapatera', vecoId, cebId, CURRENT_TIMESTAMP, NULL),
        ('CONSCAB', 'Cabangahan', vecoId, conId, CURRENT_TIMESTAMP, NULL),
        ('CONSCAN', 'Cansaga', vecoId, conId, CURRENT_TIMESTAMP, NULL),
        ('CONSCAS', 'Casili', vecoId, conId, CURRENT_TIMESTAMP, NULL),
        ('CONSCUB', 'Cubacub', vecoId, conId, CURRENT_TIMESTAMP, NULL),
        ('CONSDAN', 'Danlag', vecoId, conId, CURRENT_TIMESTAMP, NULL),
        ('CONSGAR', 'Garing', vecoId, conId, CURRENT_TIMESTAMP, NULL),
        ('CONSJUG', 'Jugan', vecoId, conId, CURRENT_TIMESTAMP, NULL),
        ('CONSLAM', 'Lamac', vecoId, conId, CURRENT_TIMESTAMP, NULL),
        ('CONSLAN', 'Lanipga', vecoId, conId, CURRENT_TIMESTAMP, NULL),
        ('CONSNAN', 'Nangka', vecoId, conId, CURRENT_TIMESTAMP, NULL),
        ('CONSPBLCN', 'Poblacion', vecoId, conId, CURRENT_TIMESTAMP, NULL),
        ('CONSPBLCNOCD', 'Poblacion Occidental', vecoId, conId, CURRENT_TIMESTAMP, NULL),
        ('CONSPBLCNORN', 'Poblacion Oriental', vecoId, conId, CURRENT_TIMESTAMP, NULL),
        ('CONSPIT', 'Pitogo', vecoId, conId, CURRENT_TIMESTAMP, NULL),
        ('CONSPNS', 'Panas', vecoId, conId, CURRENT_TIMESTAMP, NULL),
        ('CONSPNYPY', 'Panoypoy', vecoId, conId, CURRENT_TIMESTAMP, NULL),
        ('CONSPOL', 'Polog', vecoId, conId, CURRENT_TIMESTAMP, NULL),
        ('CONSPUL', 'Pulpogan', vecoId, conId, CURRENT_TIMESTAMP, NULL),
        ('CONSSAC', 'Sacsac', vecoId, conId, CURRENT_TIMESTAMP, NULL),
        ('CONSTAY', 'Tayud', vecoId, conId, CURRENT_TIMESTAMP, NULL),
        ('CONSTIL', 'Tilhaong', vecoId, conId, CURRENT_TIMESTAMP, NULL),
        ('CONSTOL', 'Tolotolo', vecoId, conId, CURRENT_TIMESTAMP, NULL),
        ('CONSTUG', 'Tugbongan', vecoId, conId, CURRENT_TIMESTAMP, NULL),
        ('DAVC10A', '10A', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC11B', '11B', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC12B', '12B', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC13B', '13B', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC14B', '14B', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC15B', '15B', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC16B', '16B', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC17B', '17B', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC18B', '18B', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC19B', '19B', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC1A', '1A', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC20B', '20B', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC21C', '21C', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC22C', '22C', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC23C', '23C', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC24C', '24C', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC25C', '25C', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC26C', '26C', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC27C', '27C', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC28C', '28C', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC29C', '29C', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC2A', '2A', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC30C', '30C', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC31D', '31D', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC32D', '32D', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC33D', '33D', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC34D', '34D', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC35D', '35D', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC36D', '36D', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC37D', '37D', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC38D', '38D', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC39D', '39D', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC3A', '3A', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC40D', '40D', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC4A', '4A', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC5A', '5A', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC6A', '6A', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC7A', '7A', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC8A', '8A', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVC9A', '9A', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCACA', 'Acacia', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCAGDPRO', 'Agdao Proper', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCALA', 'Alambre', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCANGA', 'Angalan', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCANGL', 'Angliongto', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCATAOWE', 'Atan Owe', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCBAG', 'Baganihan', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCBAGAPL', 'Bago Aplaya', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCBAGGAL', 'Bago Gallera', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCBAGPRO', 'Baguio Proper', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCBALA', 'Balagunan', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCBALING', 'Balingaeng', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCBALIOK', 'Baliok', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCBAN', 'Bantol', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCBANHEI', 'Bangkas Heights', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCBAR', 'Baracatan', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCBAT', 'Bato', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCBAY', 'Bayabas', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCBIAESC', 'Biao Escuela', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCBIAGUI', 'Biao Guianga', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCBIAJOA', 'Biao Joaquin', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCBIAMAT', 'BiaoMatina', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCBIN', 'Binugao', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCBOB', 'Bobongon', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCBUC', 'Bucana', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCBUD', 'Buda', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCBUHPRO', 'Buhangin Proper', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCBUNPRO', 'Bunawan Proper', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCCAB', 'Cabantian', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCCAD', 'Cadalian', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCCAL', 'Callawa', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCCALPRO', 'Calinan Proper', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCCAM', 'Camansi', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCCAR', 'Carmen', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCCASANG', 'Casig Ang', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCCAT', 'Catigan', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCCATGRA', 'Cat Grande', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCCATPEQ', 'Cat Pequeno', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCCAW', 'Cawayan', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCCENSANJUA', 'Centro San Juan', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCCOL', 'Colosas', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCCOM', 'Communal', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCCRSBAY', 'Crssing Bayabas', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCDAC', 'Dacudao', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCDALAG', 'Dalag', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCDALAGDAG', 'Dalagdag', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCDALIAO', 'Daliao', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCDALIAON', 'Daliaon', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCDALPLN', 'Daliaon Plnttn', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCDATSAL', 'Datu Salumay', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCDOM', 'Dominga', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCDUM', 'Dumoy', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCEDE', 'Eden', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCESP', 'Esperanza', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCFAT', 'Fatima', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCGAT', 'Gatungan', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCGOVVDUT', 'Gov V Duterte', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCGUMA', 'Gumalang', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCGUMI', 'Gumitan', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCHIZ', 'Hizon', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCILA', 'Ilang', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCINA', 'Inayangan', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCIND', 'Indangan', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCKAT', 'Katipunan', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCKIL', 'Kilate', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCKIM', 'Kimamon', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCKIN', 'Kinamayan', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCLAC', 'Lacson', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCLALIB', 'La Libertad', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCLAMA', 'Lamanan', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCLAMP', 'Lampiano', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCLAN', 'Langub', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCLAPLAP', 'Lapu Lapu', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCLAS', 'Lasang', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCLEOGAR', 'Leon Garcia', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCLIZ', 'Lizada', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCLOSAMI', 'LosAmigos', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCLUB', 'Lubogan', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCLUM', 'Lumiad', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCLUNOG', 'Lunga Og', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCMAA', 'Maa', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCMAB', 'Mabuhay', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCMAGS', 'Magsaysay', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCMAGT', 'Magtuod', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCMAGW', 'Magwawa', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCMAH', 'Mahayag', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCMALA', 'Malamba', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCMALAB', 'Malabog', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCMALAG', 'Malagos', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCMANA', 'Manambulan', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCMAND', 'Mandug', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCMANGUI', 'Manuel Guianga', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCMAP', 'Mapula', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCMAR', 'Marapangi', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCMARPRO', 'Marilog Proper', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCMATAPL', 'Matina Aplaya', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCMATCRO', 'Matina Crossing', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCMATPAN', 'Matina Pangi', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCMEG', 'Megcawayan', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCMIN', 'Mintal', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCMUD', 'Mudiang', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCMUL', 'Mulig', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCNEWCAR', 'New Carmen', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCNEWVAL', 'New Valencia', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCNEWVIS', 'New Visayas', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCOSH', 'Oshiro', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCPAM', 'Pampanga', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCPANA', 'Panacan', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCPAND', 'Pandaitan', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCPANG', 'Pangyan', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCPANT', 'Pantaron', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCPAQPRO', 'Paquibato Prop', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCPAREMB', 'Paradise Embac', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCPAY', 'Payalum', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCPBAN', 'P Bangoy', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCRCAS', 'R Castillo', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCRIV', 'Riverside', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCSALAP', 'Salapawan', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCSALAY', 'Salaysay', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCSALO', 'Saloy', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCSALV', 'Salvacion', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCSANANT', 'San Antonio', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCSANISI', 'San Isidro', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCSANJOS', 'San Jose', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCSANMIG', 'San Miguel', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCSANVIC', 'San Vicente', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCSAS', 'Sasa', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCSIB', 'Sibulan', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCSIRA', 'Sirawan', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCSIRI', 'Sirib', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCSTONIN', 'Sto Nino', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCSTOTOM', 'Sto Tomas', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCSUA', 'Suawan', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCSUB', 'Subasta', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCSUM', 'Sumimao', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCTAC', 'Tacunan', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCTAGA', 'Tagakpan', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCTAGL', 'Tagluno', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCTAGU', 'Tagurano', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCTALA', 'Talandang', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCTALO', 'Talomo', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCTALPRO', 'Talomo Proper', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCTALRIV', 'Talomo River', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCTAMA', 'Tamayong', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCTAMB', 'Tambobong', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCTAMU', 'Tamugan', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCTAP', 'Tapak', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCTAW', 'Tawan Tawan', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCTIBULOY', 'Tibuloy', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCTIBUNG', 'Tibungco', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCTIG', 'Tigatto', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCTMON', 'T Monteverde', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCTORPOB', 'Toril Poblacion', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCTUGPRO', 'Tugbok Proper', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCTUL', 'Tulalian', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCTUN', 'Tungkalan', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCUBA', 'Ubalde', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCULA', 'Ula', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCWAA', 'Waan', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCWAN', 'Wangan', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCWAQU', 'WAquino', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DAVCWIN', 'Wines', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('DUJCCABANG', 'Cabay Angan', vecoId, dujId, CURRENT_TIMESTAMP, NULL),
        ('DUJCDUJ', 'Dujali', vecoId, dujId, CURRENT_TIMESTAMP, NULL),
        ('DUJCNEWCAS', 'New Casay', vecoId, dujId, CURRENT_TIMESTAMP, NULL),
        ('DUJCSAL', 'Salvacion',  vecoId, dujId, CURRENT_TIMESTAMP, NULL),
        ('DUJCTAN', 'Tanglaw', vecoId, dujId, CURRENT_TIMESTAMP, NULL),
        ('DUJMAG', 'Dujali Magupising', vecoId, dujId, CURRENT_TIMESTAMP, NULL),
        ('KAPCKAP', 'Kapalong' , vecoId, kapId, CURRENT_TIMESTAMP, NULL),
        ('KAPCLUN', 'Luna', vecoId, kapId, CURRENT_TIMESTAMP, NULL),
        ('KAPCPAGASA', 'PagAsa' , vecoId, kapId, CURRENT_TIMESTAMP, NULL),
        ('KAPCSAM', 'Sampao' , vecoId, kapId, CURRENT_TIMESTAMP, NULL),
        ('KAPMAM', 'Kapalong Mamacao', vecoId, kapId, CURRENT_TIMESTAMP, NULL),
        ('LILOCAL', 'Calero', vecoId, lilId, CURRENT_TIMESTAMP, NULL),
        ('LILOCAN', 'Cansaga', vecoId, lilId, CURRENT_TIMESTAMP, NULL),
        ('LILOCAS', 'Casili', vecoId, lilId, CURRENT_TIMESTAMP, NULL),
        ('LILOCAT', 'Catarman', vecoId, lilId, CURRENT_TIMESTAMP, NULL),
        ('LILOCBD', 'Cabadiangan', vecoId, lilId, CURRENT_TIMESTAMP, NULL),
        ('LILOCBNG', 'Cabangahan', vecoId, lilId, CURRENT_TIMESTAMP, NULL),
        ('LILOCOT', 'Cotcot', vecoId, lilId, CURRENT_TIMESTAMP, NULL),
        ('LILODAN', 'Danlag', vecoId, lilId, CURRENT_TIMESTAMP, NULL),
        ('LILOGAR', 'Garing', vecoId, lilId, CURRENT_TIMESTAMP, NULL),
        ('LILOJUB', 'Jubay', vecoId, lilId, CURRENT_TIMESTAMP, NULL),
        ('LILOJUG', 'Jugan', vecoId, lilId, CURRENT_TIMESTAMP, NULL),
        ('LILOLAM', 'Lamac', vecoId, lilId, CURRENT_TIMESTAMP, NULL),
        ('LILOLAN', 'Lanipga', vecoId, lilId, CURRENT_TIMESTAMP, NULL),
        ('LILOLAT', 'Lataban', vecoId, lilId, CURRENT_TIMESTAMP, NULL),
        ('LILOMUL', 'Mulao', vecoId, lilId, CURRENT_TIMESTAMP, NULL),
        ('LILONAN', 'Nangka', vecoId, lilId, CURRENT_TIMESTAMP, NULL),
        ('LILOPBLCN', 'Poblacion', vecoId, lilId, CURRENT_TIMESTAMP, NULL),
        ('LILOPBLCNOCD', 'Poblacion Occidental', vecoId, lilId, CURRENT_TIMESTAMP, NULL),
        ('LILOPBLCNORN', 'Poblacion Oriental', vecoId, lilId, CURRENT_TIMESTAMP, NULL),
        ('LILOPIT', 'Pitogo', vecoId, lilId, CURRENT_TIMESTAMP, NULL),
        ('LILOPNS', 'Panas', vecoId, lilId, CURRENT_TIMESTAMP, NULL),
        ('LILOPNYPY', 'Panoypoy', vecoId, lilId, CURRENT_TIMESTAMP, NULL),
        ('LILOPOL', 'Polog', vecoId, lilId, CURRENT_TIMESTAMP, NULL),
        ('LILOPUL', 'Pulpogan', vecoId, lilId, CURRENT_TIMESTAMP, NULL),
        ('LILOSAC', 'Sacac', vecoId, lilId, CURRENT_TIMESTAMP, NULL),
        ('LILOSNCRZ', 'Santa Cruz', vecoId, lilId, CURRENT_TIMESTAMP, NULL),
        ('LILOSNRQ', 'San Roque', vecoId, lilId, CURRENT_TIMESTAMP, NULL),
        ('LILOSNVC', 'San Vicente', vecoId, lilId, CURRENT_TIMESTAMP, NULL),
        ('LILOTAB', 'Tabla', vecoId, lilId, CURRENT_TIMESTAMP, NULL),
        ('LILOTAY', 'Tayud', vecoId, lilId, CURRENT_TIMESTAMP, NULL),
        ('LILOTIL', 'Tilhaong', vecoId, lilId, CURRENT_TIMESTAMP, NULL),
        ('LILOTOL', 'Tolotolo', vecoId, lilId, CURRENT_TIMESTAMP, NULL),
        ('LILOTUG', 'Tugbongan', vecoId, lilId, CURRENT_TIMESTAMP, NULL),
        ('LILOYAT', 'Yati', vecoId, lilId, CURRENT_TIMESTAMP, NULL),
        ('MANDALA', 'Alang Alang', vecoId, mandId, CURRENT_TIMESTAMP, NULL),
        ('MANDBAK', 'Bakilid', vecoId, mandId, CURRENT_TIMESTAMP, NULL),
        ('MANDBAN', 'Banilad', vecoId, mandId, CURRENT_TIMESTAMP, NULL),
        ('MANDBAS', 'Basak', vecoId, mandId, CURRENT_TIMESTAMP, NULL),
        ('MANDCAB', 'Cabancalan', vecoId, mandId, CURRENT_TIMESTAMP, NULL),
        ('MANDCAD', 'Cadulawan', vecoId, mingId, CURRENT_TIMESTAMP, NULL),
        ('MANDCAL', 'Calajoan', vecoId, mingId, CURRENT_TIMESTAMP, NULL),
        ('MANDCAM7', 'Camp7', vecoId, mingId, CURRENT_TIMESTAMP, NULL),
        ('MANDCAM8', 'Camp8', vecoId, mingId, CURRENT_TIMESTAMP, NULL),
        ('MANDCAMB', 'Cambaro', vecoId, mandId, CURRENT_TIMESTAMP, NULL),
        ('MANDCASILI', 'Casili', vecoId, mandId, CURRENT_TIMESTAMP, NULL),
        ('MANDCASUN', 'Casuntingan', vecoId, mandId, CURRENT_TIMESTAMP, NULL),
        ('MANDCENTR', 'Centro', vecoId, mandId, CURRENT_TIMESTAMP, NULL),
        ('MANDCNDMN', 'Canduman', vecoId, mandId, CURRENT_TIMESTAMP, NULL),
        ('MANDCNTRO', 'Cantro', vecoId, mandId, CURRENT_TIMESTAMP, NULL),
        ('MANDCUA', 'Cuanos', vecoId, mingId, CURRENT_TIMESTAMP, NULL),
        ('MANDCUB', 'Cubacub', vecoId, mandId, CURRENT_TIMESTAMP, NULL),
        ('MANDEST', 'Estancia', vecoId, mandId, CURRENT_TIMESTAMP, NULL),
        ('MANDGUIND', 'Guindarohan', vecoId, mingId, CURRENT_TIMESTAMP, NULL),
        ('MANDGUIZO', 'Guizo', vecoId, mandId, CURRENT_TIMESTAMP, NULL),
        ('MANDIBA', 'Ibabao', vecoId, mandId, CURRENT_TIMESTAMP, NULL),
        ('MANDJAG', 'Jagobiao', vecoId, mandId, CURRENT_TIMESTAMP, NULL),
        ('MANDLAB', 'Labogon', vecoId, mandId, CURRENT_TIMESTAMP, NULL),
        ('MANDLIN', 'Linao', vecoId, mingId, CURRENT_TIMESTAMP, NULL),
        ('MANDLIP', 'Lipata', vecoId, mingId, CURRENT_TIMESTAMP, NULL),
        ('MANDLOO', 'Looc', vecoId, mandId, CURRENT_TIMESTAMP, NULL),
        ('MANDMAG', 'Maguikay', vecoId, mandId, CURRENT_TIMESTAMP, NULL),
        ('MANDMANDUL', 'Mandulang', vecoId, mingId, CURRENT_TIMESTAMP, NULL),
        ('MANDMANDUW', 'Manduwang', vecoId, mingId, CURRENT_TIMESTAMP, NULL),
        ('MANDMANT', 'Mantuyong', vecoId, mandId, CURRENT_TIMESTAMP, NULL),
        ('MANDOPA', 'Opao', vecoId, mandId, CURRENT_TIMESTAMP, NULL),
        ('MANDPAG', 'Pagsabungan', vecoId, mandId, CURRENT_TIMESTAMP, NULL),
        ('MANDPAKIG', 'Pakigne', vecoId, mingId, CURRENT_TIMESTAMP, NULL),
        ('MANDPAKN', 'Paknaan', vecoId, mandId, CURRENT_TIMESTAMP, NULL),
        ('MANDPOB', 'Poblacion', vecoId, mingId, CURRENT_TIMESTAMP, NULL),
        ('MANDSUB', 'Subangdaku', vecoId, mandId, CURRENT_TIMESTAMP, NULL),
        ('MANDTAB', 'Tabok', vecoId, mandId, CURRENT_TIMESTAMP, NULL),
        ('MANDTAW', 'Tawason', vecoId, mandId, CURRENT_TIMESTAMP, NULL),
        ('MANDTIB', 'Tiber', vecoId, mingId, CURRENT_TIMESTAMP, NULL),
        ('MANDTIN', 'Tingub', vecoId, mandId, CURRENT_TIMESTAMP, NULL),
        ('MANDTIP', 'Tipolo', vecoId, mandId, CURRENT_TIMESTAMP, NULL),
        ('MANDTON', 'Tongkil', vecoId, mingId, CURRENT_TIMESTAMP, NULL),
        ('MANDTUB', 'Tubod', vecoId, mingId, CURRENT_TIMESTAMP, NULL),
        ('MANDTUL', 'Tulay', vecoId, mingId, CURRENT_TIMESTAMP, NULL),
        ('MANDTUNGHAAN', 'Tungha An', vecoId, mingId, CURRENT_TIMESTAMP, NULL),
        ('MANDTUNGKOP', 'Tungkop', vecoId, mingId, CURRENT_TIMESTAMP, NULL),
        ('MANDUMA', 'Umapad', vecoId, mandId, CURRENT_TIMESTAMP, NULL),
        ('MANDVIT', 'Vito', vecoId, mingId, CURRENT_TIMESTAMP, NULL),
        ('MANDWAR1', 'Ward1', vecoId, mingId, CURRENT_TIMESTAMP, NULL),
        ('MANDWAR2', 'Ward2', vecoId, mingId, CURRENT_TIMESTAMP, NULL),
        ('MANDWAR3', 'Ward3', vecoId, mingId, CURRENT_TIMESTAMP, NULL),
        ('MANDWAR4', 'Ward4', vecoId, mingId, CURRENT_TIMESTAMP, NULL),
        ('MARAPOPAR', 'Marilog Apo Park', vecoId, davId, CURRENT_TIMESTAMP, NULL),
        ('MINGMAND', 'Manddang', vecoId, mingId, CURRENT_TIMESTAMP, NULL),
        ('MINGTUNGK', 'Tungkil', vecoId, mingId, CURRENT_TIMESTAMP, NULL),
        ('NAGAALP', 'Alpaco', vecoId, nagaId, CURRENT_TIMESTAMP, NULL),
        ('NAGABAI', 'Bairan', vecoId, nagaId, CURRENT_TIMESTAMP, NULL),
        ('NAGABAL', 'Balirong', vecoId, nagaId, CURRENT_TIMESTAMP, NULL),
        ('NAGACAB', 'Cabungahan', vecoId, nagaId, CURRENT_TIMESTAMP, NULL),
        ('NAGACAN', 'CantaoAn', vecoId, nagaId, CURRENT_TIMESTAMP, NULL),
        ('NAGACEN', 'Central Poblacion ', vecoId, nagaId, CURRENT_TIMESTAMP, NULL),
        ('NAGACOGON', 'Cogon', vecoId, nagaId, CURRENT_TIMESTAMP, NULL),
        ('NAGACOLON', 'Colon', vecoId, nagaId, CURRENT_TIMESTAMP, NULL),
        ('NAGAEASTPOB', 'East Poblacion', vecoId, nagaId, CURRENT_TIMESTAMP, NULL),
        ('NAGAINA', 'Inayagan', vecoId, nagaId, CURRENT_TIMESTAMP, NULL),
        ('NAGAINUB', 'Inuboran', vecoId, nagaId, CURRENT_TIMESTAMP, NULL),
        ('NAGAINUN', 'Inunoran', vecoId, nagaId, CURRENT_TIMESTAMP, NULL),
        ('NAGAJAG', 'Jaguimit', vecoId, nagaId, CURRENT_TIMESTAMP, NULL),
        ('NAGALANAS', 'Lanas', vecoId, nagaId, CURRENT_TIMESTAMP, NULL),
        ('NAGALANGTD', 'Langtad', vecoId, nagaId, CURRENT_TIMESTAMP, NULL),
        ('NAGALUT', 'Lutac', vecoId, nagaId, CURRENT_TIMESTAMP, NULL),
        ('NAGAMAI', 'Mainit', vecoId, nagaId, CURRENT_TIMESTAMP, NULL),
        ('NAGAMAY', 'Mayana', vecoId, nagaId, CURRENT_TIMESTAMP, NULL),
        ('NAGANAA', 'Naalad', vecoId, nagaId, CURRENT_TIMESTAMP, NULL),
        ('NAGANOR', 'North Poblacion', vecoId, nagaId, CURRENT_TIMESTAMP, NULL),
        ('NAGAPAN', 'Pangdan', vecoId, nagaId, CURRENT_TIMESTAMP, NULL),
        ('NAGAPAT', 'Patag', vecoId, nagaId, CURRENT_TIMESTAMP, NULL),
        ('NAGASOU', 'South Poblacion', vecoId, nagaId, CURRENT_TIMESTAMP, NULL),
        ('NAGATAG', 'Tagjaguimit', vecoId, nagaId, CURRENT_TIMESTAMP, NULL),
        ('NAGATAN', 'Tangke', vecoId, nagaId, CURRENT_TIMESTAMP, NULL),
        ('NAGATIN', 'Tinaan', vecoId, nagaId, CURRENT_TIMESTAMP, NULL),
        ('NAGATUY', 'Tuyan', vecoId, nagaId, CURRENT_TIMESTAMP, NULL),
        ('NAGAULI', 'Uling', vecoId, nagaId, CURRENT_TIMESTAMP, NULL),
        ('NAGAWES', 'WestPoblacion', vecoId, nagaId, CURRENT_TIMESTAMP, NULL),
        ('PANCADFLO', 'Ad Floirendo', vecoId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCBUE', 'Buenavista', vecoId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCCAC', 'Cacao', vecoId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCCAG', 'Cagangohan', vecoId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCCON', 'Consolacion', vecoId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCDAL', 'Dalisay', vecoId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCDAP', 'Dapco', vecoId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCDATABD', 'Datu Abdul', vecoId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCGRE', 'Gredu', vecoId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCJPLAU', 'Jp Laurel', vecoId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCKAS', 'Kasilak', vecoId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCKAT', 'Katipunan', vecoId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCKAU', 'Kauswagan', vecoId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCKIO', 'Kiotoy', vecoId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCLIC', 'Licanan', vecoId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCLITPAN', 'Little Panay', vecoId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCLOWPAN', 'Lower Panaga', vecoId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCMABU', 'Mabunao', vecoId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCMAD', 'Maduao', vecoId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCMAL', 'Malativas', vecoId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCMANA', 'Manay', vecoId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCNAN', 'Nanyo', vecoId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCNEWAKL', 'New Aklan', vecoId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCNEWMAL', 'New Malitbog', vecoId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCNEWPAN', 'New Pandan', vecoId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCNEWVIS', 'New Visayas', vecoId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCPAN', '', vecoId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCQUE', 'Quezon', vecoId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCSAL', 'Salvacion', vecoId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCSANFRA', 'San Francisco', vecoId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCSANNIC', 'San Nicolas', vecoId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCSANPED', 'San Pedro', vecoId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCSANROQ', 'San Roque', vecoId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCSANVIC', 'San Vicente', vecoId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCSIN', 'Sindaton', vecoId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCSOUDAV', 'Southern Davao', vecoId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCSTACRU', 'StaCruz', vecoId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCSTONIN', 'StoNino', vecoId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCTAGO', 'Tagorot', vecoId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCTAGP', 'Tagpore', vecoId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCTIB', 'Tibungol', vecoId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANCWATFAL', 'Water Falls', vecoId, panId, CURRENT_TIMESTAMP, NULL),
        ('PANKAT', 'Panabo Katualan', vecoId, panId, CURRENT_TIMESTAMP, NULL),
        ('SANFBALUD', 'Balud', vecoId, sfernId, CURRENT_TIMESTAMP, NULL),
        ('SANFBALUNGAG', 'Balungag', vecoId, sfernId, CURRENT_TIMESTAMP, NULL),
        ('SANFBAS', 'Basak', vecoId, sfernId, CURRENT_TIMESTAMP, NULL),
        ('SANFBUG', 'Bugho', vecoId, sfernId, CURRENT_TIMESTAMP, NULL),
        ('SANFCAB', 'Cabatbatan', vecoId, sfernId, CURRENT_TIMESTAMP, NULL),
        ('SANFGRE', 'Green Hills', vecoId, sfernId, CURRENT_TIMESTAMP, NULL),
        ('SANFILA', 'Ilaya', vecoId, sfernId, CURRENT_TIMESTAMP, NULL),
        ('SANFLAN', 'Lantawan', vecoId, sfernId, CURRENT_TIMESTAMP, NULL),
        ('SANFLIB', 'Liburon', vecoId, sfernId, CURRENT_TIMESTAMP, NULL),
        ('SANFMAG', 'Magsico', vecoId, sfernId, CURRENT_TIMESTAMP, NULL),
        ('SANFNOR', 'North Poblacion', vecoId, sfernId, CURRENT_TIMESTAMP, NULL),
        ('SANFPAN', 'PanadTaran', vecoId, sfernId, CURRENT_TIMESTAMP, NULL),
        ('SANFPIT', 'Pitalo', vecoId, sfernId, CURRENT_TIMESTAMP, NULL),
        ('SANFSANGAT', 'Sangat', vecoId, sfernId, CURRENT_TIMESTAMP, NULL),
        ('SANFSANISD', 'SanIsidro', vecoId, sfernId, CURRENT_TIMESTAMP, NULL),
        ('SANFSOU', 'South Poblacion', vecoId, sfernId, CURRENT_TIMESTAMP, NULL),
        ('SANFTAB', 'Tabionan', vecoId, sfernId, CURRENT_TIMESTAMP, NULL),
        ('SANFTAN', 'Tananas', vecoId, sfernId, CURRENT_TIMESTAMP, NULL),
        ('SANFTIN', 'Tinubdan', vecoId, sfernId, CURRENT_TIMESTAMP, NULL),
        ('SANFTON', 'Tonggo', vecoId, sfernId, CURRENT_TIMESTAMP, NULL),
        ('SANFTUB', 'Tubod', vecoId, sfernId, CURRENT_TIMESTAMP, NULL),
        ('STOTOMNEWKAT', 'New Katipunan', vecoId, stomId, CURRENT_TIMESTAMP, NULL),
        ('STOTOMNEWVIS', 'New Visayas', vecoId, stomId, CURRENT_TIMESTAMP, NULL),
        ('STOTOMSAL', 'Salvacion', vecoId, stomId, CURRENT_TIMESTAMP, NULL),
        ('STOTOMSANVIC', 'San Vicente', vecoId, stomId, CURRENT_TIMESTAMP, NULL),
        ('TALBIA', 'Biasong', vecoId, talId, CURRENT_TIMESTAMP, NULL),
        ('TALBUL', 'Bulacao', vecoId, talId, CURRENT_TIMESTAMP, NULL),
        ('TALCAM', 'Camp4', vecoId, talId, CURRENT_TIMESTAMP, NULL),
        ('TALCANDUL', 'Candulawan', vecoId, talId, CURRENT_TIMESTAMP, NULL),
        ('TALCANSOJ', 'Cansojong', vecoId, talId, CURRENT_TIMESTAMP, NULL),
        ('TALDUM', 'Dumlog', vecoId, talId, CURRENT_TIMESTAMP, NULL),
        ('TALJAC', 'Jaclupan', vecoId, talId, CURRENT_TIMESTAMP, NULL),
        ('TALLAG', 'Lagtang', vecoId, talId, CURRENT_TIMESTAMP, NULL),
        ('TALLAW', 'Lawaan', vecoId, talId, CURRENT_TIMESTAMP, NULL),
        ('TALLAW2', 'Lawaan2', vecoId, talId, CURRENT_TIMESTAMP, NULL),
        ('TALLAW3', 'Lawaan3', vecoId, talId, CURRENT_TIMESTAMP, NULL),
        ('TALLIN', 'Linao', vecoId, talId, CURRENT_TIMESTAMP, NULL),
        ('TALMAG', 'Maghaway', vecoId, talId, CURRENT_TIMESTAMP, NULL),
        ('TALMAN', 'Manipis', vecoId, talId, CURRENT_TIMESTAMP, NULL),
        ('TALMOH', 'Mohon', vecoId, talId, CURRENT_TIMESTAMP, NULL),
        ('TALPOB', 'Poblacion', vecoId, talId, CURRENT_TIMESTAMP, NULL),
        ('TALPOO', 'Pook', vecoId, talId, CURRENT_TIMESTAMP, NULL),
        ('TALSANISD', 'San Isidro', vecoId, talId, CURRENT_TIMESTAMP, NULL),
        ('TALSANROQ', 'San Roque', vecoId, talId, CURRENT_TIMESTAMP, NULL),
        ('TALTAB', 'Tabunok', vecoId, talId, CURRENT_TIMESTAMP, NULL),
        ('TALTAN', 'Tangke', vecoId, talId, CURRENT_TIMESTAMP, NULL),
        ('TALTAP', 'Tapol', vecoId, talId, CURRENT_TIMESTAMP, NULL) ON CONFLICT (code, distribution_utility_id, city_id) DO NOTHING;
END $$;
